{"name": "Test - crud record ", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './testdata/ACS/provisioning_record_H248.json'", "trace": "self = <testcase.ACS.test_api_acs.TestACSAPI object at 0x0000014006502CE0>, base_api = <utils.base_api_acs.BaseAPIACS object at 0x00000140063F7B50>\n\n    @allure.title('Test - crud record ')\n    # #@pytest.mark.skip()\n    def test_crud(self,base_api):\n        global model_id\n    \n        # create a record\n        file_name_key = endpoint +'_create'\n>       json_data = load_json(file_path[file_name_key])\n\ntestcase\\ACS\\test_api_acs.py:119: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\npath = './testdata/ACS/provisioning_record_H248.json'\n\n    def load_json(path):\n>       with open(path, encoding=\"utf-8\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: './testdata/ACS/provisioning_record_H248.json'\n\nutils\\data_handler.py:14: FileNotFoundError"}, "parameters": [{"name": "base_api", "value": "'aws'"}], "start": 1747910049127, "stop": 1747910049127, "uuid": "50f717cb-b80e-4648-8df4-dd32f0efe820", "historyId": "e0368cb26c69a57c6ff762005b9bd52f", "testCaseId": "88d0999a3449e613d98ad344fae0a1a5", "fullName": "testcase.ACS.test_api_acs.TestACSAPI#test_crud", "labels": [{"name": "parentSuite", "value": "testcase.ACS"}, {"name": "suite", "value": "test_api_acs"}, {"name": "subSuite", "value": "TestACSAPI"}, {"name": "host", "value": "Cherry-640879"}, {"name": "thread", "value": "24568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.ACS.test_api_acs"}]}